    const { useState, useEffect, useRef } = React;

    const FEED_JSON_URL = "https://raw.githubusercontent.com/cipinzas-hash/feeder/main/modules/feed/data/feed.json";
    const CINE_JSON_URL = "https://raw.githubusercontent.com/cipinzas-hash/feeder/main/modules/feed/data/cine.json";
    const CINE_CATEGORIAS = ["Películas", "Series", "Animación"];
    const VITRINA_CATEGORIAS = [...CINE_CATEGORIAS, "Microdocumentales", "Melee", "Conciertos"];
    const VITRINA_ICONS = { "Películas": "🎬", "Series": "📺", "Animación": "⛩️", "Microdocumentales": "🎥", "Melee": "🕹️", "Conciertos": "🎪" };
    const NOTICIAS_CATEGORIA = "Noticias";
    const MUSIC_CATEGORIA = "Dark scene / Música";
    const CAT_COLORS = { "Melee": "#ff6600", "Pokémon TCG": "#ffcc00", "Gaming": "#5c9cff", "Noticias": "#e91e8c", "Películas": "#e91e8c", "Series": "#e91e8c", "Animación": "#e91e8c", "Microdocumentales": "#26a69a", "Podcasts": "#ffcc00", "Dark scene / Música": "#7b4fd4", "Ciencia / Conocimiento": "#2e7d52", "Tecnología": "#26a69a", "Poliamor": "#aac756" };
    const FORMATO_BY_CATEGORIA = { "Películas": "cine", "Series": "cine", "Animación": "cine", [MUSIC_CATEGORIA]: "musica" };
    const REFRESH_THROTTLE_MS = 4 * 60 * 60 * 1000;
    const STORAGE_KEY = "angst-feed-proto-v1";

    function fetchJsonSafe(url) { return fetch(url, { cache: "no-store" }).then(r => r.ok ? r.json() : null).catch(() => null); }
    function roundRobinMerge(arrays) { const queues = arrays.map(c => ({ ...c, items: [...c.items] })); const out = []; let more = true; while (more) { more = false; for (const q of queues) if (q.items.length) { out.push(q.items.shift()); more = true; } } return out; }
    async function fetchFeedData() {
      const [feedData, cineData] = await Promise.all([fetchJsonSafe(FEED_JSON_URL), fetchJsonSafe(CINE_JSON_URL)]);
      if (!feedData && !cineData) throw new Error("no se pudo leer el feed");
      const merged = {};
      for (const data of [feedData, cineData]) for (const c of (data?.categories || [])) {
        const formato = FORMATO_BY_CATEGORIA[c.cat] || (data === cineData ? "cine" : "lectura");
        merged[c.cat] = [...(merged[c.cat] || []), ...(c.items || []).map(it => ({ ...it, formato }))];
      }
      const vitrina = {}, feedCats = [];
      for (const [cat, items] of Object.entries(merged)) VITRINA_CATEGORIAS.includes(cat) ? vitrina[cat] = items : feedCats.push({ cat, items });
      return { queue: roundRobinMerge(feedCats), vitrina, diag: feedCats.map(c => ({ cat: c.cat, count: c.items.length, withText: c.items.filter(i => i.fullText || (i.tipo === "video" && i.videoId)).length })), generatedAt: feedData?.generatedAt || cineData?.generatedAt || null };
    }
    function loadState() { try { const r = localStorage.getItem(STORAGE_KEY); return r ? JSON.parse(r) : null; } catch { return null; } }
    function saveState(s) { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(s)); } catch {} }
    const btnGhost = { flex: 1, background: "transparent", border: "1px dashed #444", color: "#aaa", borderRadius: 10, padding: "10px 6px", fontFamily: "'DM Sans',sans-serif", fontSize: 10, cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "center", gap: 2 };
    function primaryAction(tipo) { if (tipo === "video") return { icon: "▶️", label: "ver" }; if (tipo === "podcast") return { icon: "🎧", label: "escuchar" }; return { icon: "⬆️", label: "leer" }; }
    function shareToWhatsApp(item) { window.open(`https://wa.me/?text=${encodeURIComponent(`${item.title}\n${item.link}`)}`, "_blank"); }
    function FormatoTag({ item }) { const b = item.tipo === "video" ? "VID" : item.tipo === "podcast" ? "AUD" : item.fullText ? "TXT" : null; return b ? <div style={{display:"flex",gap:6,justifyContent:"center",marginBottom:8}}><span style={{fontFamily:"'DM Sans',sans-serif",fontSize:10,fontWeight:800,color:"#fff",background:{VID:"#e0483e",AUD:"#9b59d0",TXT:"#6b7280"}[b],padding:"3px 8px",borderRadius:4}}>{b}</span></div> : null; }

    function PodcastPlayer({ item, onClose }) {
      const audioRef = useRef(null); const [playing, setPlaying] = useState(false); const [current, setCurrent] = useState(0); const [duration, setDuration] = useState(0);
      useEffect(() => { setPlaying(false); setCurrent(0); setDuration(0); if (audioRef.current) { audioRef.current.pause(); audioRef.current.load(); } }, [item?.guid]);
      if (!item) return null;
      const fmt = s => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2,"0")}`;
      return <div style={{position:"fixed",left:12,right:12,bottom:"calc(62px + env(safe-area-inset-bottom))",zIndex:500,background:"#151515",border:"1px solid rgba(255,255,255,.12)",borderRadius:14,padding:10,boxShadow:"0 12px 40px rgba(0,0,0,.55)"}}>
        <div style={{display:"flex",gap:10,alignItems:"center"}}>
          {item.image ? <img src={item.image} alt="" style={{width:58,height:58,borderRadius:8,objectFit:"cover",background:"#222"}} /> : <div style={{width:58,height:58,borderRadius:8,background:"#ffcc00",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24}}>🎙️</div>}
          <div style={{flex:1,minWidth:0}}><div style={{fontFamily:"'DM Sans',sans-serif",fontSize:10,color:"#ffcc00",fontWeight:700}}>META POD</div><div style={{fontFamily:"'Caveat',cursive",fontSize:18,color:"#fff",fontWeight:700,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{item.title}</div><div style={{fontFamily:"'DM Sans',sans-serif",fontSize:10,color:"#777"}}>{fmt(current)} / {fmt(duration)}</div></div>
          <button onClick={async()=>{if(audioRef.current?.paused){await audioRef.current.play();setPlaying(true);}else{audioRef.current?.pause();setPlaying(false);}}} style={{width:42,height:42,borderRadius:"50%",border:"none",background:"#ffcc00",fontSize:18,cursor:"pointer"}}>{playing?"❚❚":"▶"}</button>
          <button onClick={onClose} style={{background:"transparent",border:"none",color:"#666",fontSize:18,cursor:"pointer"}}>×</button>
        </div>
        <input type="range" min="0" max={duration || 0} value={Math.min(current,duration || 0)} onChange={e=>{const v=Number(e.target.value);if(audioRef.current)audioRef.current.currentTime=v;setCurrent(v);}} style={{width:"100%",marginTop:8}} />
        <audio ref={audioRef} src={item.audioUrl} onLoadedMetadata={e=>setDuration(e.currentTarget.duration||0)} onTimeUpdate={e=>setCurrent(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} />
      </div>;
    }

    function MetaPodBanner({ item, onListen }) { if (!item) return null; return <button onClick={()=>onListen(item)} style={{width:"100%",minHeight:150,border:"1px solid rgba(255,204,0,.35)",borderRadius:14,background:"linear-gradient(135deg,#241f00,#111 65%)",color:"#fff",padding:18,textAlign:"left",cursor:"pointer",display:"flex",alignItems:"center",gap:16,boxShadow:"0 8px 24px rgba(0,0,0,.3)"}}>
      {item.image ? <img src={item.image} alt="Meta Pod" style={{width:92,height:92,borderRadius:12,objectFit:"cover",flexShrink:0}} /> : <div style={{width:92,height:92,borderRadius:12,background:"#ffcc00",color:"#111",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'DM Sans',sans-serif",fontWeight:900,fontSize:24,flexShrink:0}}>MP</div>}
      <div style={{flex:1,minWidth:0}}><div style={{fontFamily:"'DM Sans',sans-serif",fontSize:10,fontWeight:800,color:"#ffcc00",letterSpacing:1}}>NUEVO EPISODIO</div><div style={{fontFamily:"'Caveat',cursive",fontSize:30,fontWeight:700,lineHeight:1.05}}>META POD</div><div style={{fontFamily:"'DM Sans',sans-serif",fontSize:12,color:"rgba(255,255,255,.65)",marginTop:5,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{item.title}</div><div style={{fontFamily:"'DM Sans',sans-serif",fontSize:11,color:"#ffcc00",marginTop:9}}>▶ ESCUCHAR</div></div>
    </button>; }

    function PodcastFeed({ items, onListen }) { const [seen,setSeen]=useState(()=>{try{return new Set(JSON.parse(localStorage.getItem("angst-feed-podcasts-escuchados-v1")||"[]"))}catch{return new Set()}}); const meta=items.filter(i=>i.source==="Meta Pod"); const latest=meta[0]; if(!latest)return <div style={{padding:40,textAlign:"center",color:"#555"}}>Meta Pod todavía no tiene episodios disponibles.</div>; return <div style={{padding:"16px 18px 100px"}}><MetaPodBanner item={latest} onListen={onListen}/><div style={{marginTop:18}}>{meta.map(i=><div key={i.guid} style={{padding:"16px 0",borderBottom:"1px solid #222",opacity:seen.has(i.guid)?.55:1}}><div style={{fontFamily:"'Caveat',cursive",fontSize:21,color:"#fff",fontWeight:700}}>{i.title}</div>{i.summary&&<div style={{fontFamily:"'DM Sans',sans-serif",fontSize:12,color:"#777",lineHeight:1.5,margin:"6px 0 10px"}}>{i.summary}</div>}<button onClick={()=>{const n=new Set(seen);n.add(i.guid);setSeen(n);try{localStorage.setItem("angst-feed-podcasts-escuchados-v1",JSON.stringify([...n]))}catch{ }onListen(i)}} style={{...btnGhost,borderColor:"#ffcc00",color:"#ffcc00"}}>🎧 escuchar</button></div>)}</div></div>; }

    function StoryCard({ item, onSkip, onExpand, onSave, onChangeCategory, onShuffle, onOpenBuzon, onOpenDiag, hasDiag, onRefresh, canRefresh, refreshing, buzonCount }) { const color=CAT_COLORS[item.categoria]||"#888"; return <div style={{position:"fixed",inset:0,background:"#0a0a0a",display:"flex",flexDirection:"column"}}><div style={{flex:1,position:"relative",overflow:"hidden"}}>{item.image?<img src={item.image} alt="" style={{width:"100%",height:"100%",objectFit:"cover",opacity:.5}}/>:null}<div style={{position:"absolute",inset:0,background:"linear-gradient(to top,rgba(0,0,0,.92),rgba(0,0,0,.15) 55%,rgba(0,0,0,.55))"}}/><div style={{position:"absolute",top:16,left:16,right:58}}><span style={{fontFamily:"'DM Sans',sans-serif",fontSize:10,color:"#111",background:color,borderRadius:20,padding:"4px 12px",fontWeight:700}}>{item.categoria}</span></div><div style={{position:"absolute",bottom:0,left:0,right:0,padding:20}}><FormatoTag item={item}/><div style={{fontFamily:"'Caveat',cursive",fontSize:28,fontWeight:700,color:"#fff"}}>{item.title}</div><div style={{fontFamily:"'DM Sans',sans-serif",fontSize:13,color:"rgba(255,255,255,.6)",lineHeight:1.5}}>{item.summary}</div></div></div><div style={{display:"flex",gap:6,padding:"10px 10px calc(10px + 50px + env(safe-area-inset-bottom))",background:"#111"}}><button onClick={onChangeCategory} style={btnGhost}>⬅️ categoría</button><button onClick={onSave} style={btnGhost}>⬇️ guardar</button><button onClick={onExpand} style={{...btnGhost,background:color,color:"#111",borderColor:color}}>{primaryAction(item.tipo).icon} {primaryAction(item.tipo).label}</button><button onClick={onSkip} style={btnGhost}>➡️ siguiente</button></div></div>; }

    function ExtendedView({item,onBack,onNext,onSave,onChangeCategory}) { return <div style={{position:"fixed",inset:0,background:"#0d0d0d",display:"flex",flexDirection:"column",zIndex:50}}><div style={{padding:"14px 18px",display:"flex",alignItems:"center",gap:10,borderBottom:"1px solid #1a1a1a"}}><button onClick={onBack} style={{background:"transparent",border:"none",color:"#666",fontSize:20}}>←</button><span style={{flex:1,color:"#777",fontSize:11}}>{item.source}</span></div><div style={{flex:1,overflowY:"auto",padding:20}}><FormatoTag item={item}/><div style={{fontFamily:"'Caveat',cursive",fontSize:26,fontWeight:700,color:"#fff",marginBottom:14}}>{item.title}</div>{item.tipo==="podcast"&&item.audioUrl?<audio controls src={item.audioUrl} style={{width:"100%",marginBottom:14,colorScheme:"dark"}}/>:null}{item.fullText?<div className="article-body" style={{fontFamily:"'DM Sans',sans-serif",fontSize:15,color:"rgba(255,255,255,.8)",lineHeight:1.7}} dangerouslySetInnerHTML={{__html:item.fullText}}/>:<div style={{color:"#777",fontSize:13}}>{item.summary}</div>}</div><div style={{display:"flex",gap:6,padding:10,background:"#111"}}><button onClick={onChangeCategory} style={btnGhost}>⬅️ anterior</button><button onClick={onSave} style={btnGhost}>⬇️ guardar</button><button onClick={onNext} style={{...btnGhost,background:CAT_COLORS[item.categoria]||"#fff",color:"#111"}}>➡️ siguiente</button></div></div>; }

    function VitrinaView({vitrinaData,onOpen,onListen}) { const cats=VITRINA_CATEGORIAS; return <div style={{paddingBottom:70,background:"#111",minHeight:"100vh"}}><div style={{padding:"16px 18px 4px"}}><span style={{fontFamily:"'Caveat',cursive",fontSize:24,fontWeight:700,color:"#fff"}}>🎬 vitrina audiovisual</span></div><div style={{display:"flex",gap:6,padding:"12px 18px",overflowX:"auto"}}>{cats.map(c=><button key={c} onClick={()=>onOpen({__category:c})} style={{padding:"9px 14px",fontSize:12,border:"1px solid #333",borderRadius:20,background:"transparent",color:"#999"}}>{VITRINA_ICONS[c]||c}</button>)}</div><div style={{padding:"0 18px"}}>{cats.map(c=>c==="Melee"||c==="Conciertos"||c==="Microdocumentales"?<div key={c} style={{padding:"20px 0",color:"#777"}}>{c}</div>:null)}</div></div>; }

    function TabBar({area,onChange,buzonCount,onOpenBuzon}) { return <div style={{position:"fixed",left:0,right:0,bottom:0,display:"flex",background:"#111",zIndex:40,paddingBottom:"env(safe-area-inset-bottom)"}}><button onClick={()=>onChange("noticias")} style={{flex:1,padding:10,background:"transparent",border:"none",color:area==="noticias"?"#fff":"#666"}}>📰 Noticias</button><button onClick={()=>onChange("vitrina")} style={{flex:1,padding:10,background:"transparent",border:"none",color:area==="vitrina"?"#fff":"#666"}}>🎬 Vitrina</button><button onClick={onOpenBuzon} style={{flex:1,padding:10,background:"transparent",border:"none",color:"#666"}}>📌 {buzonCount}</button></div>; }

    function FeedPage({onExit}) {
      const ExitBtn=()=> <button onClick={onExit} style={{position:"fixed",top:10,right:12,zIndex:999,background:"rgba(0,0,0,.55)",color:"#fff",border:"none",borderRadius:20,width:34,height:34}}>✕</button>;
      const [loaded,setLoaded]=useState(false),[queue,setQueue]=useState([]),[seen,setSeen]=useState([]),[buzon,setBuzon]=useState([]),[lastRefresh,setLastRefresh]=useState(null),[view,setView]=useState("end"),[refreshing,setRefreshing]=useState(false),[refreshMsg,setRefreshMsg]=useState(null),[refreshDiag,setRefreshDiag]=useState([]),[feedGeneratedAt,setFeedGeneratedAt]=useState(null),[area,setArea]=useState("noticias"),[vitrinaData,setVitrinaData]=useState({}),[playerItem,setPlayerItem]=useState(null);
      const queueRef=useRef([]),seenRef=useRef([]),buzonRef=useRef([]),lastRefreshRef=useRef(null); useEffect(()=>{queueRef.current=queue},[queue]);useEffect(()=>{seenRef.current=seen},[seen]);useEffect(()=>{buzonRef.current=buzon},[buzon]);useEffect(()=>{lastRefreshRef.current=lastRefresh},[lastRefresh]);
      function persist(o={}){saveState({feedQueue:o.queue??queueRef.current,feedSeen:o.seen??seenRef.current,feedBuzon:o.buzon??buzonRef.current,feedLastRefresh:o.lastRefresh??lastRefreshRef.current});}
      useEffect(()=>{const s=loadState();if(s){setQueue(s.feedQueue||[]);setSeen(s.feedSeen||[]);setBuzon(s.feedBuzon||[]);setLastRefresh(s.feedLastRefresh||null);if((s.feedQueue||[]).length)setView("story");}setLoaded(true);fetchFeedData().then(({vitrina})=>setVitrinaData(vitrina||{})).catch(()=>{});},[]);
      const canRefresh=!lastRefresh||(Date.now()-new Date(lastRefresh).getTime())>REFRESH_THROTTLE_MS;
      async function doRefresh(){if(refreshing||!canRefresh)return;setRefreshing(true);setRefreshMsg("actualizando…");try{const r=await fetchFeedData();setRefreshDiag(r.diag);setFeedGeneratedAt(r.generatedAt);setVitrinaData(r.vitrina||{});const known=new Set([...seenRef.current,...buzonRef.current.map(x=>x.guid),...queueRef.current.map(x=>x.guid)]);const fresh=r.queue.filter(x=>!known.has(x.guid));const nq=[...queueRef.current,...fresh];setQueue(nq);const ts=new Date().toISOString();setLastRefresh(ts);persist({queue:nq,lastRefresh:ts});if(nq.length)setView("story");setRefreshMsg(fresh.length?`✓ ${fresh.length} nuevas`:`sin novedades`);}catch{setRefreshMsg("error al actualizar")}setRefreshing(false);setTimeout(()=>setRefreshMsg(null),3000);}
      function advance(){setQueue(q=>{const [cur,...rest]=q;if(cur){const ns=[...seenRef.current,cur.guid].slice(-5000);setSeen(ns);persist({queue:rest,seen:ns});}if(!rest.length)setView("end");return rest;});}
      function handleSave(){const cur=queueRef.current[0];if(!cur)return;const nb=[...buzonRef.current,cur];setBuzon(nb);persist({buzon:nb});advance();}
      if(!loaded)return <><div style={{position:"fixed",inset:0,background:"#0a0a0a"}}/><ExitBtn/></>;
      const current=queue[0];
      return <div style={{fontFamily:"'DM Sans',sans-serif"}}>{refreshMsg&&<div style={{position:"fixed",top:20,left:"50%",transform:"translateX(-50%)",background:"#fff",color:"#111",padding:"8px 18px",borderRadius:20,zIndex:200}}>{refreshMsg}</div>}{area==="vitrina"?<VitrinaView vitrinaData={vitrinaData} onOpen={()=>{}} onListen={setPlayerItem}/>:<>{view==="story"&&current&&<StoryCard item={current} onSkip={advance} onExpand={()=>setView("extended")} onSave={handleSave} onChangeCategory={()=>{}} onShuffle={()=>{}} onOpenBuzon={()=>{}} onOpenDiag={()=>{}} hasDiag={!!refreshDiag.length} onRefresh={doRefresh} canRefresh={canRefresh} refreshing={refreshing} buzonCount={buzon.length}/>} {view==="extended"&&current&&<ExtendedView item={current} onBack={()=>setView("story")} onNext={()=>{advance();setView("story")}} onSave={handleSave} onChangeCategory={()=>setView("story")}/>} {view==="end"&&<div style={{position:"fixed",inset:0,background:"#0a0a0a",display:"flex",alignItems:"center",justifyContent:"center",color:"#777"}}><button onClick={doRefresh} disabled={!canRefresh} style={{background:"#fff",border:0,borderRadius:20,padding:"10px 20px"}}>↻ buscar novedades</button></div>}</>}{playerItem&&<PodcastPlayer item={playerItem} onClose={()=>setPlayerItem(null)}/>}<TabBar area={area} onChange={setArea} buzonCount={buzon.length} onOpenBuzon={()=>{}}/><ExitBtn/></div>;
    }
    export default FeedPage;
